"""adiciona coluna telefone na tabela pessoas

Revision ID: 358e74da56d9
Revises: fcd99156fdfa
Create Date: 2026-03-20 10:37:37.472013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358e74da56d9'
down_revision: Union[str, Sequence[str], None] = 'fcd99156fdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pessoas', sa.Column('telefone', sa.String(), nullable=True))
    op.create_index(op.f('ix_Pessoas_telefone'), 'Pessoas', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pessoas_telefone'), table_name='Pessoas')
    op.drop_column('Pessoas', 'telefone')
    # ### end Alembic commands ###
