"""Criando tabela de pessoas

Revision ID: fcd99156fdfa
Revises: 
Create Date: 2026-03-19 16:43:26.592734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd99156fdfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('estudante', 'professor', 'coordenador', 'admin', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Pessoas_email'), 'Pessoas', ['email'], unique=True)
    op.create_index(op.f('ix_Pessoas_id'), 'Pessoas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pessoas_id'), table_name='Pessoas')
    op.drop_index(op.f('ix_Pessoas_email'), table_name='Pessoas')
    op.drop_table('Pessoas')
    # ### end Alembic commands ###
